# veta-app/pubspec.yaml
name: veta_app
description: A veterinary platform marketplace mobile app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.1.0
  provider: ^6.1.1
  record: ^5.0.1
  audioplayers: ^5.2.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  file_picker: ^5.5.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  sqflite_common_ffi_web: ^0.4.0
  path: ^1.8.3
  badges: ^3.1.2
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  uuid: ^4.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Questrial
      fonts:
        - asset: assets/fonts/Questrial-Regular.ttf
          weight: 500

   assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/background/
